# Site wide configuration

title:            
locale:           en_US
url: https://cadurosar.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Carlos Eduardo Rosar Kos Lassance
  avatar: bio-photo.png
  bio: "AI researcher, video-game aficionado and proud supporter of Coritiba F.C."
  email: carlos.rosarkoslassance at imt-atlantique dot fr
  disqus-shortname:
  twitter: #cadurosar
  facebook: #cadurosar
  google:
    plus: #cadurosar
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: cadurosar
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: carlos-eduardo-lassance
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
